<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <WindowsPackageType>None</WindowsPackageType>
    <RootNamespace>WinCal</RootNamespace>
    <AssemblyName>WinCal</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\..\Assets\WinCal.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.0" />
    <PackageReference Include="Ical.Net" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\Assets\WinCal.ico" />
  </ItemGroup>

</Project>
